import type { TrainingPlan } from '@/types';

export const TRAINING_PLANS: TrainingPlan[] = [
  { id: '63kg-beginner', title: '63kg级入门训练计划', weightClass: '63kg', difficulty: 'beginner', duration: '6周', description: '适合刚接触腕力训练的新手，注重基础力量和关节稳定性。', tags: ['入门','基础力量'], exercises: [{ name: '腕弯举 (Wrist Curl)', sets: '3组', reps: '12-15次', notes: '轻重量，注重控制' }, { name: '旋前训练 (Pronation)', sets: '3组', reps: '10-12次', notes: '弹力带或绳索' }, { name: '握力训练', sets: '3组', reps: '保持30秒', notes: '握力器或毛巾悬挂' }, { name: '二头弯举', sets: '3组', reps: '10-12次' }, { name: '前臂伸展', sets: '2组', reps: '15次', notes: '防止不平衡' }] },
  { id: '63kg-intermediate', title: '63kg级爆发力训练计划', weightClass: '63kg', difficulty: 'intermediate', duration: '8周', description: '提高爆发力和技术动作，包含实战模拟。', tags: ['爆发力','技术'], exercises: [{ name: '爆发腕弯举', sets: '4组', reps: '8-10次', notes: '快速爆发慢速下放' }, { name: '侧压模拟', sets: '4组', reps: '每侧10次', notes: '绳索模拟侧压' }, { name: '旋前爆发', sets: '3组', reps: '8-10次' }, { name: '勾手练习', sets: '3组', reps: '12次', notes: '弹力带或搭档' }, { name: '悬垂练习', sets: '3组', reps: '保持45秒' }] },
  { id: '70kg-intermediate', title: '70kg级耐力训练计划', weightClass: '70kg', difficulty: 'intermediate', duration: '6周', description: '提升耐力和持续性，适合有一定基础的选手。', tags: ['耐力','持续性'], exercises: [{ name: '高次腕弯举', sets: '4组', reps: '15-20次', notes: '中等重量' }, { name: '持续握力', sets: '3组', reps: '保持60秒' }, { name: '弹力带对抗', sets: '3组', reps: '每侧20次' }, { name: '绳索卷重', sets: '3组', reps: '5圈' }, { name: '倒立撑', sets: '3组', reps: '8-10次' }] },
  { id: '78kg-advanced', title: '78kg级综合力量计划', weightClass: '78kg', difficulty: 'advanced', duration: '10周', description: '全面力量提升，涵盖速度、力量和技巧的平衡发展。', tags: ['综合','力量'], exercises: [{ name: '大重量腕弯举', sets: '5组', reps: '5-8次', notes: '逐步增加负荷' }, { name: '爆发旋前', sets: '4组', reps: '6-8次' }, { name: '上升力训练', sets: '4组', reps: '10次', notes: '龙门架' }, { name: '背压训练', sets: '4组', reps: '8-10次' }, { name: '肩部推举', sets: '4组', reps: '8-12次' }, { name: '实战对练', sets: '3组', reps: '每轮3分钟' }, { name: '核心训练', sets: '3组', reps: '15次' }] },
  { id: '86kg-advanced', title: '86kg级专项强化计划', weightClass: '86kg', difficulty: 'advanced', duration: '8周', description: '专注侧压和勾手技术，强化核心竞争力量。', tags: ['侧压','勾手'], exercises: [{ name: '侧压专项', sets: '5组', reps: '每侧8次', notes: '大重量侧压模拟' }, { name: '勾手对抗', sets: '4组', reps: '每侧10次' }, { name: '腕力桌面', sets: '4组', reps: '每侧8次' }, { name: '上臂弯举', sets: '4组', reps: '8-12次' }, { name: '技术对练', sets: '3组', reps: '每轮5分钟' }] },
  { id: '95kg-intermediate', title: '95kg级进阶训练计划', weightClass: '95kg', difficulty: 'intermediate', duration: '8周', description: '结合力量和技术，为大级别选手提供全面进阶方案。', tags: ['进阶','组合'], exercises: [{ name: '组合腕力训练', sets: '4组', reps: '每动作10次', notes: '多动作循环' }, { name: '顶卷 (Top Roll)', sets: '4组', reps: '10次' }, { name: '勾手+侧压转换', sets: '3组', reps: '每侧8次' }, { name: '负重悬垂', sets: '3组', reps: '保持30秒' }, { name: '鞭打训练', sets: '3组', reps: '15次' }, { name: '指力训练', sets: '3组', reps: '12次' }] },
  { id: '105kg-advanced', title: '105kg级力量突破计划', weightClass: '105kg', difficulty: 'advanced', duration: '12周', description: '针对大级别选手的力量突破，专注最大力量和锁定能力。', tags: ['力量突破','大重量'], exercises: [{ name: '极限腕弯举', sets: '5组', reps: '3-5次', notes: '接近极限重量' }, { name: '旋前锁定', sets: '5组', reps: '保持10秒', notes: '等长收缩' }, { name: '重负荷勾手', sets: '4组', reps: '5-8次' }, { name: '侧压爆发', sets: '4组', reps: '6次' }, { name: '离心训练', sets: '3组', reps: '5次', notes: '慢速离心快速向心' }, { name: '辅助训练', sets: '3组', reps: '10-12次' }] },
  { id: '105kg-plus-elite', title: '105kg+级王者训练计划', weightClass: '105kg+', difficulty: 'advanced', duration: '12周', description: '为最高级别选手设计，周期化训练和赛前准备。', tags: ['王者','周期化'], exercises: [{ name: '周期化腕力', sets: '按周变化', reps: '3-12次', notes: '递减→力量→爆发周期' }, { name: '全能技术循环', sets: '4组', reps: '每技术8次', notes: '顶卷+勾手+侧压' }, { name: '极限握力', sets: '4组', reps: '保持20秒' }, { name: '赛前模拟', sets: '3组', reps: '5分钟' }, { name: '恢复训练', sets: '2组', reps: '15次', notes: '轻重量' }, { name: '核心力量', sets: '4组', reps: '12次' }, { name: '灵活性训练', sets: '2组', reps: '每关节10次' }] },
];
